<div class="full-page register-page section-image" data-color="orange" data-image="../../assets/img/bg5.jpg">
    <div class="content">
        <div class="container">
            <div class="card card-register card-plain text-center">
                <div class="card-header ">
                    <div class="row  justify-content-center">
                        <div class="col-md-8">
                            <div class="header-text">
                                <h2 class="card-title">Permohonan Izin </h2>
                                <H5 class="card-subtitle">Data Surat Tugas</H5>
                                <hr />
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-body ">
                    <form class='form-horizontal' id='submit' action="addst" method='post' enctype='multipart/form-data'>

                        <?php
                        foreach ($reg as $a) :
                            $ID_REG = $a->ID_REG;
                            if ($a->JENIS == "lab") {
                                $JENIS = "Izin Operasional Laboraturium";
                            } else if ($a->JENIS == "pend") {
                                $JENIS = "Izin Operasional Pendidikan";
                            } else if ($a->JENIS == "kons") {
                                $JENIS = "Izin Jasa Konstruksi";
                            }
                            $NAMA = $a->NAMA;
                            $ALAMAT = $a->ALAMAT;
                            $KELURAHAN = $a->KELURAHAN;
                            $KECAMATAN = $a->KECAMATAN;
                            $KOTA = $a->KOTA;
                            $PROVINSI = $a->PROVINSI;
                            $PENANGGUNG_JAWAB = $a->PENANGGUNG_JAWAB;
                            $NO_TELP = $a->NO_TELP;
                        endforeach;
                        ?>

                        <div class="row" style="color:white">
                            <input type=hidden value="<?php echo $a->ID_REG; ?>" name="id_reg" id="id_reg">
                            <input type=hidden value="<?php echo $a->NAMA; ?>" name="nama" id="nama">
                            <input type=hidden value="<?php echo $a->ALAMAT; ?>" name="alamat" id="alamat">
                            <input type=hidden value="<?php echo $a->KELURAHAN; ?>" name="kelurahan" id="kelurahan">
                            <input type=hidden value="<?php echo $a->KECAMATAN; ?>" name="kecamatan" id="kecamatan">
                            <input type=hidden value="<?php echo $a->KOTA; ?>" name="kota" id="kota">
                            <input type=hidden value="<?php echo $a->PROVINSI; ?>" name="provinsi" id="provinsi">
                            <input type=hidden value="<?php echo $a->PENANGGUNG_JAWAB; ?>" name="penanggung_jawab" id="penanggung_jawab">

                            <div class="col-md-6">
                                <div class="row">
                                    <div class="col-md-6">
                                        No Surat Tugas :
                                    </div>
                                    <div class="col-md-6">
                                        <input readonly type="text" class="form-control" placeholder="Autogenerated" name="no_surat" id="no_surat">
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="row">
                                    <div class="col-md-6">
                                        No BAP :
                                    </div>
                                    <div class="col-md-6">
                                        <input readonly type="text" class="form-control" placeholder="Autogenerated" name="no_bap" id="no_bap">
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="row">
                                    <div class="col-md-6">
                                        Tanggal Surat Tugas :
                                    </div>
                                    <div class="col-md-6">
                                        <input  type="date" class="form-control"  name="tgl" id="tgl" required>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="row">
                                    <div class="col-md-6">
                                        Petugas 1
                                    </div>
                                    <div class="col-md-6">
                                        <select class="form-control" name="nip1" id="nip1" required>
                                            
                                            <?php

                                            foreach ($nip as $a) :
                                                echo "<option value='$a->NIP'>$a->NIP || $a->NAMA</option>";
                                            endforeach;
                                            ?>

                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="row">
                                    <div class="col-md-6">
                                        Petugas 2
                                    </div>
                                    <div class="col-md-6">
                                        <select class="form-control" name="nip2" id="nip2" required>
                                          
                                            <?php

                                            foreach ($nip as $a) :
                                                echo "<option value='$a->NIP'>$a->NIP || $a->NAMA</option>";
                                            endforeach;
                                            ?>

                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <button type="submit" class="btn btn-primary">Surat Tugas</button>
                        </div>
                        <br>
                        <table style="width:100%">
                            <tr align="Left">
                                <td>
                                    ID Registrasi
                                </td>
                                <td>
                                    <?php
                                    echo $ID_REG
                                    ?>
                                </td>
                                <td>
                                    Jenis
                                </td>
                                <td>
                                    <?php
                                    echo $JENIS
                                    ?>
                                </td>

                            </tr>
                            <tr align="Left">
                                <td>
                                    Nama Izin
                                </td>
                                <td>
                                    <?php
                                    echo $NAMA
                                    ?>
                                </td>
                                <td>
                                    Alamat Izin
                                </td>
                                <td>
                                    <?php
                                    echo $ALAMAT
                                    ?>
                                </td>

                            </tr>
                            <tr align="Left">
                                <td>
                                    Kelurahan
                                </td>
                                <td>
                                    <?php
                                    echo $KELURAHAN
                                    ?>
                                </td>
                                <td>
                                    Kecamatan
                                </td>
                                <td>
                                    <?php
                                    echo $KECAMATAN
                                    ?>
                                </td>

                            </tr>
                            <tr align="Left">
                                <td>
                                    Kota
                                </td>
                                <td>
                                    <?php
                                    echo $KOTA
                                    ?>
                                </td>
                                <td>
                                    Provinsi
                                </td>
                                <td>
                                    <?php
                                    echo $PROVINSI
                                    ?>
                                </td>

                            </tr>
                            <tr align="Left">
                                <td>
                                    Penannggu Jawab
                                </td>
                                <td>
                                    <?php
                                    echo $PENANGGUNG_JAWAB
                                    ?>
                                </td>
                                <td>
                                    No Telepon
                                </td>
                                <td>
                                    <?php
                                    echo $NO_TELP
                                    ?>
                                </td>

                            </tr>
                            <tr align="Left">
                                <td>
                                    ID Registrasi
                                </td>
                                <td>
                                    contoh
                                </td>
                                <td>
                                    Jenis
                                </td>
                                <td>
                                    COntoh
                                </td>

                            </tr>
                        </table>
                        <br>

                    </form>

                </div>
            </div>
        </div>
    </div>